version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-root}

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=algafood
    ports:
      - 3306:3306
    volumes:
      - algafood_db:/var/lib/mysql

volumes:
  algafood_db:
    driver: local