version: '3'

services:
  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
    ports:
      - 3306:3306
    volumes:
      - "./.docker/mysql/data:/var/lib/mysql"
