version: '3.9'

networks:
  algafood-network:
    driver: bridge

services:
  algafood-api:
    image: allissonabn/algafood-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=development
      - SPRING_DATASOURCE_URL=jdbc:mysql://algafood-db:3306/algafood?createDatabaseIfNotExist=true&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=${MYSQL_USERNAME:-root}
      - SPRING_DATASOURCE_PASSWORD=${MYSQL_PASSWORD:-root}
    ports:
      - 8080:8080
    networks:
      - algafood-network
    depends_on:
      - algafood-db
    restart: on-failure

  algafood-db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=algafood
    ports:
      - 3306:3306
    networks:
      - algafood-network
    volumes:
      - algafood-db:/var/lib/mysql

volumes:
  algafood-db:
    driver: local
