ALTER TABLE pedido MODIFY COLUMN data_confirmacao DATETIME NULL;
ALTER TABLE pedido MODIFY COLUMN data_entrega DATETIME NULL;
ALTER TABLE pedido MODIFY COLUMN data_cancelamento DATETIME NULL;
ALTER TABLE pedido MODIFY COLUMN status ENUM('CRIADO', 'CONFIRMADO', 'ENTREGUE', 'CANCELADO') NOT NULL DEFAULT 'CRIADO';
